# saving dir : $saving_dir/${first_name}_{last_name}_{experiment_name}/
first_name: aliso
last_name: Baghernezhad
experiment_name: second
gesture_duration: 1 
rest_duration: 1
number_of_gesture_repetition: 1 
emg_frequency: 2000
IMU_frequency: 200
camera_fps: 60
phase1_wait: 5
file_path: /home/user/data/example.txt
date: 11122024
slides_images_path: experiment1_images
saving_dir: ./data/
saving_dir_noraxon: /data_noraxon/
merged_imu_path: "./merged_imu.csv"
merged_emg_path: "./merged_emg.csv"
processed_data_dir : "./processed_data/"
