# saving dir : $saving_dir/${first_name}_{last_name}_{experiment_name}/
first_name: testing
last_name: workflow
experiment_name: 10
gesture_duration: 2
rest_duration: 2
number_of_gesture_repetition: 4
number_of_gestures: 15
emg_frequency: 2000
IMU_frequency: 200
camera_fps: 60
phase1_wait: 5
window_size: 150
overlapping: 75
save_model : True
model_path: /model/
file_path: /home/user/data/example.txt
date: 17122024
slides_images_path: experiment1_images
saving_dir: ./data/
saving_dir_noraxon: /data_noraxon/
merged_imu_path: "./merged_imu.csv"
merged_emg_path: "./merged_emg.csv"
processed_data_dir : "./processed_data/"
nsensors: 8
W1: 1
W2: 2
W3: 3
W4: 4
F1: 5
F2: 6
F3: 7
F4: 8
load_features: False
load_models: False
feature_selection: True